== Introduction

Code review is a measure for assuring software quality by letting developers read the code of others. While the primary goal is to increase quality by finding defects, it also fosters learning and mutual code ownership.

Continuous integration / continuous delivery (CI/CD) is commonly seen as a prerequisite to faster delivery of cloud-based products. This comprises the ability to review, test, and, if required, veto changes before they affect every other developer working on the same repository.  This capability to validate a change in isolation before integrating it is also known as link:https://trunkbaseddevelopment.com/game-changers/#google-s-internal-devops-2006-onwards[proposed commits] or link:https://martinfowler.com/bliki/PendingHead.html[pending head]. For instance, most git platforms have implemented this concept as depicted below.

[ditaa]
....
       *          /--------\
       |       /--+ Rework +<-----------------\
       v       |  \--------/               No |
   /-------\   v  /-----------\  /--------\   |  Yes /---------\
   |Request+--><>-+ Automated +->+  Peer  +-><>----->| Submit  |
   \-------/      |  Review   |  | Review |          | (merge) |
                  \-----------/  \--------/  OK?     \---------/
                                                          |
                                                          v
                                                         /\
                                                         \/
....

Once your source repository supports such a validation, manual change-based code reviews usually come for free because it does not matter technically whether a change is vetoed by a human vote or an automated test verdict.
While Git platforms like Gerrit Changes and link:https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/reviewing-changes-in-pull-requests[GitHub Pull Requests] already support the concept of proposed commits out of the box, ABAP Change and Transport System (CTS) so far only offers extension points where a comparable flow can be implemented besides or on top to veto the release of transport requests.

This document provides an overview of possible scenarios which can be implemented in various development landscapes.

== Related Work

Some work has already been done to apply git-based code reviews for ABAP:

* link:https://blogs.sap.com/2018/03/23/abap-code-reviews-with-abapgit/[ABAP code reviews with abapGit] by Eduardo Copat, describes the general idea of exporting code to GitHub using abapGit to review it via Pull Requests.
* link:https://blogs.sap.com/2020/01/30/how-we-do-abap-code-review-using-abapgit/[How we do ABAP code review using abapGit] by Michael Pang, explains how to use the abapGit feature *transport to branch* to review a CTS transport before it is released.
* link:https://blogs.sap.com/2020/08/05/create-a-commit-in-git-when-an-abap-task-is-released/[Create a commit in Git when an ABAP task is released] by Karin Spiegel, elaborates on code reviews per transport by using existing BAdI interfaces to commit changes per task release to a feature branch using gCTS.
