== Tools
In this section we look at tools for conducting code reviews in the context of ABAP development.

=== Git
link:https://en.wikipedia.org/wiki/Git[Git] is a popular distributed version control system, which helps developers work on the same codebase. Unlike ABAP, git works with files instead of objects in a database, which allows editing any file with
any favorite editor, and keeping multiple copies (branches) of all files.

Git is a protocol, and is typically used in connection with cloud-based hosting platforms like:

* link:https://github.com[GitHub]
* link:https://gitlab.com[GitLab]
* link:https://bitbucket.com[Bitbucket]
* link:https://azure.microsoft.com/en-us/services/devops/repos/[Azure Repos]

For an introduction to git see:

link:https://git-scm.com/doc[Git Documentation], including reference manual and videos

link:https://guides.github.com/introduction/git-handbook/[Git Handbook] by GitHub

=== Code Review Platforms
Git helps keeping track of changes to files, and the git hosting platforms add extra functionality on top of that. As explained in the <<_introduction>>, the most important feature is *proposed commits*, which is the basis for code reviews.
The general idea is to keep all commits of a feature in a separate branch, propose to merge this branch to a parent or main branch, and to conduct a review conversation over this proposal.

For instance, GitHub provides link:https://github.com/features/code-review/[Code Reviews via Pull Requests]. Other git platforms offer similar features.

=== CTS
The Change and Transport System (CTS) helps you to organize development projects in the ABAP Workbench and in Customizing, and then transport the changes between the SAP systems in your system landscape.

The complete documentation on how to configure CTS and how to set up transport landscapes is available on the SAP Help Portal at link:https://help.sap.com/viewer/4a368c163b08418890a406d413933ba7/201809.002/en-US/48c4300fca5d581ce10000000a42189c.html[Change and Transport System].

CTS also offers the possibility to integrate custom check implementations in the flow of transport requests via the BAdI `CTS_REQUEST_CHECK`.
In particular, the method `CHECK_BEFORE_RELEASE` is useful for vetoing the release of transports based on external conditions, like code reviews.

=== ABAP and Git
ABAP objects are stored in the underlying database, and git works on files, to enable git in ABAP, the
objects must be serialized to files and moved to the git server via the git protocol. Currently two different
tools exists that brings git and ABAP together.

==== abapGit
link:https://abapGit.org[abapGit] is a git client written in ABAP for use with ABAP, it serializes the ABAP objects  to files, and provides access to the most common git operations.

It can be link:https://docs.abapgit.org/guide-install.html[installed] on any SAP system version 702 and up, requiring only a ABAP developer key for installation.

abapGit was initially released in link:https://blogs.sap.com/2014/07/17/git-client-for-abap-alpha-release/[2014] and is continuously being enhanced, users can choose to update to the latest version at any time.
link:https://dotabap.org[Multiple open source projects] use abapGit for development and installation into systems.

==== gCTS
A first set of features of git-enabled CTS (gCTS) is available with SAP S/4HANA 1909. You can find the documentation on how to configure and use gCTS on the SAP Help Portal: link:https://help.sap.com/viewer/4a368c163b08418890a406d413933ba7/201909.000/en-US/f319b168e87e42149e25e13c08d002b9.html[Git-enabled Change and Transport System]. A good starting point is Karin Spiegel's blog post link:https://blogs.sap.com/2019/11/14/gcts-is-here/[gCTS is here].

To get the idea of gCTS and what is planned for future releases, please refer to its link:https://support.sap.com/content/dam/support/en_us/library/ssp/tools/Software-logistic-tools/Ideas_CI_ABAP_V3.pdf[statement of direction].

=== Static Analysis and Tests

To make code reviews effective, it is useful to conduct automated checks upfront. For instance, machines are much cheaper and more effective at finding typical slip errors by static code analysis than human reviewers. Hence it is desirable to perform such checks upfront before peer code reviewers are bothered with a change.

Git platforms usually allow developers to connect continuous integration pipelines to their repositories so that arbitrary automated checks can be configured.
In the following, we will look into tools running ABAP-specific checks in such pipelines.

==== abaplint
link:https://abaplint.org[abaplint] is a open source static analysis tool for ABAP, it works on files serialized by abapGit. Execution typically happens for each push to git running on a pipeline.

The abaplint configuration file `abaplint.json` is stored in the repository along with the code.
// todo, I'll probably rewrite some of this, plus add a link to https://abaplint.app -Hvam
// todo, link https://github.com/abaplint/abaplint/blob/main/docs/ci/README.md
To let the developer check their working copy, link:https://github.com/abaplint/abaplint-sci-client[abaplint-sci-client] can be setup. And the linter also works in vscode or running standalone in a browser window.

==== Code Inspector (ATC)
The developer can use link:https://help.sap.com/viewer/c238d694b825421f940829321ffa326a/7.51.7/en-US/4ec5711c6e391014adc9fffe4e204223.html[ATC] to check the working copy in an ABAP system.

If the state of the ABAP system matches the git state, ATC can be executed an information given in the pull request to help the code reviewer.

In addition to the checks in the standard system, there are open source projects which provides additional checks:

* link:https://github.com/SAP/code-pal-for-abap[code pal for ABAP]
* link:https://abapopenchecks.org[abapOpenchecks]

It is however not so trivial (yet) to execute ATC as part of a pipeline.

One possibility is to use BAdI `CTS_REQUEST_CHECK` to execute ATC programmatically during the release of a transport.

//todo which release was ADT first introduced with?
In case the SAP ABAP Development Tools for Eclipse are already configured for your system, you could use its REST APIs to trigger ATC and ABAP Unit externally. This is what, for instance, the pipeline step link:https://www.project-piper.io/steps/gctsExecuteABAPUnitTests/[gctsExecuteABAPUnitTests] of project Piper does.

Additionally, it is possible to upload and download the Code Inspector variant via link:https://blogs.sap.com/2015/08/02/upload-and-download-code-inspector-variants-via-xml/[upDOWNci] and stored in link:https://github.com/larshp/upDOWNci/issues/12[git]

// todo: how to call ATC for more than the developer's working copy
With SAP BTP ABAP Environment (a.k.a. link:https://blogs.sap.com/2019/08/20/its-steampunk-now/[Steampunk]) and newer SAP S/4HANA releases, there is also the possibility to use dedicated REST end-points for such continuous integration scenarios. There is even a dedicated link:https://www.project-piper.io/pipelines/abapEnvironment/introduction/[ABAP Environment Pipeline] for that.
These newer features are of course not available to customers working on older releases.

=== abap-openapi-client

External check services often have an link:https://swagger.io/docs/specification/about/[OpenAPI] definition. Unfortunately, there is no standard way of consuming such OpenAPI services in ABAP yet.

// todo,
https://github.com/abap-openapi/abap-openapi-client